### ISSUE TITLE
more straight forward development usage

### ISSUE THREAD

**Issue by TristanWright** [Kitware/simput#19]
A watch command for types for quicker type development would be a good start. 
My flow recently has been:

``` sh
Simput -t pyfr -o versions/ -c src/ && Simput -a versions/pyfr.js && simput -o . -t pyfr
```

everytime I have a change in the types 😕

**Comment by TristanWright** [comment]
you can do

```
simput -t pyfr -c src/ -o versions/ -a
```

to add the file right after compiling it

**Comment by aronhelser** [comment]
This is addressed by new:
npm run dev
npm run type:*
which has automatic reload after single type compile command. In the docs now.
