### ISSUE TITLE
importing file does not update active view

### ISSUE THREAD

**Issue by TristanWright** [Kitware/simput#20]
See attached gif, the parts where the mouse is invisible I'm choosing the file from the system (which screen capturers in chrome to not pick up). I upload a file where the Pr value is 72000 and I need to switch to another view and back to see the changes.

![untitled gif](https://cloud.githubusercontent.com/assets/13318121/19664271/e0c648e6-99fc-11e6-911a-924ec03d0834.gif)

**Comment by aronhelser** [comment]
Not an issue in the new UI.
