### ISSUE TITLE
Simput cli misbehaving

### ISSUE THREAD

**Issue by aronhelser** [Kitware/simput#46]
I used 'npm link' so the 'Simput' command would point to my local checkout. With the new Vue.js UI, if I do:

`Simput` or `Simput -t oscillator` 

or if I do what is currently in the documentation, like for pyfr:

`Simput -i samples/empty/pyfr-empty-externals.json -o samples/empty/`

the app exits without output. I have to do:

`Simput -t oscillator -i /tmp`

for it to start.

 @jourdain

**Comment by jourdain** [comment]
Indeed this is misbehaving as the working ones should not. ;-)
Then maybe we should allow the plain `Simput` to work although it is kind of nice to just type `Simput` to know what you can do with that CLI.

**Comment by aronhelser** [comment]
Sorry, I missed what the problem was. If I do what is currently in the documentation, like for pyfr:

`Simput -i samples/empty/pyfr-empty-externals.json -o samples/empty/`

the app exits without output. The command that works is 

`Simput -i`

with nothing or anything after the -i, doesn't seem to matter.

**Comment by aronhelser** [comment]
For me, that command exits with no output.

**Comment by jourdain** [comment]
Good, that just mean we need to fix the CLI and the doc.

**Comment by aronhelser** [comment]
The other thing we may want to fix - if you drag a 'model.json' file to the input box, and then save, it saves a file ending '.json' which is actually a zip file.

**Comment by jourdain** [comment]
Oh yes that would be good.

**Comment by aronhelser** [comment]
OK, I'll take a look.

**Comment by aronhelser** [comment]
The vcard `samples/example/FakeAddressBook.json` no longer converts correctly. It's simple key-value pairs,
```json
    "data": {
        "AddressBook": [
            {
                "firstName": "Sebastien",
                "lastName": "Jourdain",
                "street": "Somewhere",
                "city": "Santa Fe",
                "state": "NM",
                "zip": "87507",
                "country": "USA"
            },{
```

Should that work, or should I just update it to the current .simput.model format?

**Comment by jourdain** [comment]
update to the `.simput.model`. Thx!

**Comment by aronhelser** [comment]
Next issue! 😺 
The `-a` flag no longer updates the type - it still puts the file in `~/.Simput/`, but the app is only paying attention to `static/types`.  How should we handle the `-a` flag now?

**Comment by jourdain** [comment]
Remove it... Those old behaviors when we had a server does not make sense anymore.

**Comment by aronhelser** [comment]
That affects the list and remove flags too - I'll remove those too. I'll switch over to `npm` commands for the docs. 

`npm run dev` in one window and `npm run type:vcard` in the other, I think?

**Comment by jourdain** [comment]
Anything that require fs access are now invalid. So yes for those other flags and any other that I may forget here. Then we need to make sure the cli is somewhat consistent/make-sense as only 2 modes are available (run / compile-type).

The `npm run dev` should only be for development when we look for incremental build. 

The issue with using the npm command is that users could think they should be able to run `npm run type:my-unkown-type` to compile their own and will complain that it does not work. That does not teach them how to compile and deploy a type. For the mainstream ones we could have a section that mention the shortcut we have via npm but truly we should not remove `how to compile a type with the Simput command`.

**Comment by aronhelser** [comment]
Hmm. I think the instructions for how to compile a type should be 'add your type to package.json following the pattern' - because you have to be in the right directory for it to work.

**Comment by aronhelser** [comment]
I have a rework of the CLI to just two modes almost done.

**Comment by jourdain** [comment]
That is not true (no need to be in a specific directory to work). But the thing that is not worked out yet is how to register your type like we do it [here](https://github.com/Kitware/simput/blob/master/static/index.html#L34-L37).
Knowing that those types could be hosted anywhere...

**Comment by aronhelser** [comment]
Done enough....
