### ISSUE TITLE
fail to save oscillator

### ISSUE THREAD

**Issue by Trophime** [Kitware/simput#57]
Trying to follow the docs related to oscillator,
I've created an oscillator "osc1".
When trying to save the output with the "save" button, it gives me the following error:
```
Simput: 3.0.0
Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0


[Vue warn]: Error in event handler for "click": "TypeError: dataModel.data.run[0] is undefined"

found in

---> <VBtn>
       <VToolbar>
         <VApp>
           <DragAndDrop> at src/components/widgets/DragAndDrop/index.vue
             <App> at src/components/core/App/index.vue
               <Root>,TypeError: dataModel.data.run[0] is undefined
```

**Comment by jourdain** [comment]
For that type, you need to visit all the pages (left menu). I guess the convert script assume data everywhere while it could have been written in a more conservative / fault-tolerant manner.

**Comment by Trophime** [comment]
The error was actually linked with an empty object in my type.
So you can close this issue.

Netherless I have some questions:
* is the default value for a choice item is assigned or not? It seems that one has to actually select the value from the sliding menu to really assign the field. That's why I end up with an empty object. Is there a way to avoid this behaviour
* What happens when you clik on save button? Where is the zip outfile actually saved? I cannot find any zip file in my simput server (run from a docker)...

Thanks for your explanations
Best 
C

**Comment by jourdain** [comment]
1) The value is not set when let to default but it is up to the converter to use the default value of the model when that one was not set.

2) The zip get downloaded to the machine that run the browser on the client side. Same as when you download a file with your browser.

**Comment by Trophime** [comment]
Thanks.

1. something like: dataModel.data.models[0].models.name.default[0] to get the default?
2. strange... nothing is actually downloaded when I clik on save
How can I debug this?

**Comment by jourdain** [comment]
Does any error pop-up? Maybe in the developer console?

For the default, I don't necessary recall. But you can import the model.{js|json} inside your convert function which will then let you access anything you've defined.
